homolog:
   url: http://www.google.com
   some_api_url: https://some_api:8080
   whatever_api_url: http://whatever:8000

desenv:
   url: http://www.hotmail.com
   some_api_url: https://some_api:8080
   whatever_api_url: http://whatever:8000
